#!/bin/sh
while read file
do
        case "$1" in
        "C-d")
                mv "$file" ~/.trash
                notify-send -u critical -t 700 "SXIV" "Photo Deleted";;
        "C-r")
                convert -rotate 90 "$file" "$file";;
        "C-c")
                echo -n "$file" | xclip -selection clipboard
                notify-send -u low -t 700 "SXIV" "Photo Copied to clipboard";;
        "C-w")
                cp "$file" ".config/wall.png"
                xwallpaper --zoom .config/wall.png
                notify-send -u low -t 700 "SXIV" "Wallpaper Changed";;
        "C-z")
                mv "/.trash/$file" "./$file"
                notify-send -u low -t 700 "SXIV" "Photo Restored";;
        esac
done
