#!/bin/sh
# A script to initialize a programing project
# Author: Bishr Ghalil

echo -n "Project's Name: "
read pjt_name

pjt_folder=$(pwd)"/"$pjt_name
echo [#] Creating Project At: $pjt_folder

echo "[#] Making dirs $pjt_name, github, src"

mkdir $pjt_folder
mkdir -p $pjt_folder/github
mkdir -p $pjt_folder/src


echo "[#] Making files README.md, gitignore, LICENSE (MIT), Makefile"

touch $pjt_folder/.gitignore
cp $HOME/Scripts/LICENSE $pjt_folder/
echo "# $pjt_name" > "$pjt_folder/README.md"
touch "$pjt_folder/Makefile"
echo "all: install
install:
    cp $pjt_name /usr/bin
uninstall:
    rm -rf /usr/bin/$pjt_name" > "$pjt_folder/Makefile"


echo "[#] Git..."
cd $pjt_name
git init
git add .
git commit -m "First commit"


echo "[#] Done."
